# Generated by Django 2.1.3 on 2018-11-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsh_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evententry',
            old_name='event',
            new_name='event_type',
        ),
    ]
