# Generated by Django 2.1.3 on 2018-11-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsh_rest', '0002_auto_20181117_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententry',
            name='value_type',
        ),
    ]
